#!/bin/sh

install_brew() {
  # Proudly borrowed from:
  # https://github.com/duckfullstop/dotfiles/blob/f734eea399a7ccd1c25b57242997e79f230abc4d/.config/yadm/bootstrap

  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

# Install Homebrew 
echo "Setting up Homebrew..."
install_brew

echo "Setting up Hyprland..."

# Run Waybar installation
echo "Setting up Waybar..."
"$HOME/.config/yadm/hyprland/waybar.sh"

echo "Bootstrap completed."
